export const categoryList = [
  {
    id: 1,
    value: 'shoes',
    label: 'shoes',
  },
  {
    id: 2,
    value: 'shirts',
    label: 'shirts',
  },
  {
    id: 3,
    value: 'T-shirts',
    label: 'T-shirts',
  },
  {
    id: 4,
    value: 'watches',
    label: 'watches',
  },
  {
    id: 5,
    value: 'bags',
    label: 'bags',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Comfy t-shirt',
    Brand: 'H&M',
    category: 'T-shirts',
    price: 2500,
    coverSrc: '/images/t-shirt/tshirt3.jpeg',
  },
  {
    id: 2,
    title: 'trekking shoes',
    Brand: 'Qunecha',
    category: 'shoes',
    price: 1000,
    coverSrc: '/images/shoes/shoes4.png',
  },
  {
    id: 3,
    title: 'digital watch',
    Brand: 'Noise',
    category: 'watches',
    price: 2000,
    coverSrc: '/images/watches/watch1.jpg',
  },
  {
    id: 4,
    title: 'sneakers shoes',
    Brand: 'Nike',
    category: 'shoes',
    price: 1800,
    coverSrc: '/images/shoes/shoes3.png',
  },
  {
    id: 5,
    title: 'formal shirt',
    Brand: 'Zara',
    category: 'shirts',
    price: 2000,
    coverSrc: '/images/shirts/shirt1.jpeg',
  },
  {
    id: 6,
    title: 'casual t-shirt',
    Brand: 'H&M',
    category: 'T-shirts',
    price: 3500,
    coverSrc: '/images/t-shirt/tshirt2.png',
  },
  {
    id: 7,
    title: 'high ankle shoes',
    Brand: 'Puma',
    category: 'shoes',
    price: 2200,
    coverSrc: '/images/shoes/shoes1.jpg',
  },
  {
    id: 8,
    title: 'printed party shirt',
    Brand: 'Arrow',
    category: 'shirts',
    price: 1900,
    coverSrc: '/images/shirts/shirt2.jpg',
  },
  {
    id: 9,
    title: 'formal shoes',
    Brand: 'Bata',
    category: 'shoes',

    price: 2750,
    coverSrc: '/images/shoes/shoes2.png',
  },
  {
    id: 10,
    title: 'Gym wear t-shirt',
    Brand: 'Puma',
    category: 'T-shirts',
    price: 4350,
    coverSrc: '/images/t-shirt/tshirt1.jpg',
  },
  {
    id: 11,
    title: 'diamond watch',
    Brand: 'Rolex',
    category: 'watches',
    price: 3300,
    coverSrc: '/images/watches/watch2.png',
  },
  {
    id: 12,
    title: 'laptop bag',
    Brand: 'Dell',
    category: 'bags',
    price: 4100,
    coverSrc: '/images/bags/bag1.jpg',
  },
];
